-- Schema rollout for the Ralph foundation slice.
-- Apply this on PostgreSQL before deploying code that writes:
--   1) extraction_evidence.source_locator_json
--   2) filing_attempt

ALTER TABLE extraction_evidence
ADD COLUMN IF NOT EXISTS source_locator_json TEXT;

ALTER TABLE extraction_evidence
ADD COLUMN IF NOT EXISTS source_heading_path_json TEXT;

ALTER TABLE extraction_evidence
ADD COLUMN IF NOT EXISTS source_block_offsets_json TEXT;

ALTER TABLE extraction_evidence
ADD COLUMN IF NOT EXISTS adequacy_signals_json TEXT;

ALTER TABLE extraction_evidence
ADD COLUMN IF NOT EXISTS retry_history_json TEXT;

CREATE TABLE IF NOT EXISTS filing_attempt (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id VARCHAR(64) NOT NULL,
    route VARCHAR(16) NOT NULL,
    accession_no VARCHAR(32) NOT NULL,
    cik VARCHAR(10),
    accepted_at TIMESTAMPTZ,
    status VARCHAR(16) NOT NULL,
    error_type VARCHAR(64),
    error_detail TEXT,
    started_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_filing_attempt_run_route_accession
ON filing_attempt (run_id, route, accession_no);

CREATE INDEX IF NOT EXISTS ix_filing_attempt_run_id
ON filing_attempt (run_id);

CREATE INDEX IF NOT EXISTS ix_filing_attempt_accession_no
ON filing_attempt (accession_no);
